version: "3"

networks:
    php:

services:
    php0: &php
        image: ek42/webserver:1.0
        networks: [ php ]
        container_name: php0
        hostname: php0
        ports:
            - "8081:80"

    php1:
        <<: *php
        container_name: php1
        hostname: php1
        ports:
            - "8082:80"


    haproxy:
        image: haproxy:2.6
        networks: [ php ]
        hostname: haproxy
        container_name: haproxy
        ports:
            - "8080:80"
            - "1937:1937"
        volumes:
            - ./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg


